arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
use-escaping: true
# workaround for issue: https://github.com/flutter/flutter/issues/148333
synthetic-package: false
output-dir: lib/l10n/gen_l10n
nullable-getter: false