import 'dart:ui';

import 'package:invidious/models/db/server.dart';
import 'package:invidious/models/interfaces/sharelink.dart';
import 'package:invidious/models/videoInList.dart';
import 'package:json_annotation/json_annotation.dart';

import 'imageObject.dart';


part 'channel.g.dart';

@JsonSerializable()
class Channel implements ShareLinks {
  String author;
  String authorId;
  String authorUrl;
  List<ImageObject>? authorBanners;
  List<ImageObject> authorThumbnails;
  int subCount;
  int? totalViews;
  int? joined;
  bool autoGenerated;
  bool? isFamilyFriendly;
  String description;

  List<String>? allowedRegions;
  List<VideoInList>? latestVideos;

  Channel(this.author, this.authorId, this.authorUrl, this.authorBanners, this.authorThumbnails, this.subCount, this.totalViews, this.joined, this.autoGenerated, this.isFamilyFriendly,
      this.description, this.allowedRegions, this.latestVideos);


  factory Channel.fromJson(Map<String, dynamic> json) => _$ChannelFromJson(json);

  Map<String, dynamic> toJson() => _$ChannelToJson(this);

  @override
  String getInvidiousLink(Server server) {
    return '${server.url}/channel/$authorId';

  }

  @override
  String getYoutubeLink() {
    return 'https://www.youtube.com/channel/$authorId';
  }
}
