// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'channel.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Channel _$ChannelFromJson(Map<String, dynamic> json) => Channel(
      json['author'] as String,
      json['authorId'] as String,
      json['authorUrl'] as String,
      (json['authorBanners'] as List<dynamic>?)
          ?.map((e) => ImageObject.fromJson(e as Map<String, dynamic>))
          .toList(),
      (json['authorThumbnails'] as List<dynamic>)
          .map((e) => ImageObject.fromJson(e as Map<String, dynamic>))
          .toList(),
      (json['subCount'] as num).toInt(),
      (json['totalViews'] as num?)?.toInt(),
      (json['joined'] as num?)?.toInt(),
      json['autoGenerated'] as bool,
      json['isFamilyFriendly'] as bool?,
      json['description'] as String,
      (json['allowedRegions'] as List<dynamic>?)
          ?.map((e) => e as String)
          .toList(),
      (json['latestVideos'] as List<dynamic>?)
          ?.map((e) => Video.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$ChannelToJson(Channel instance) => <String, dynamic>{
      'author': instance.author,
      'authorId': instance.authorId,
      'authorUrl': instance.authorUrl,
      'authorBanners': instance.authorBanners,
      'authorThumbnails': instance.authorThumbnails,
      'subCount': instance.subCount,
      'totalViews': instance.totalViews,
      'joined': instance.joined,
      'autoGenerated': instance.autoGenerated,
      'isFamilyFriendly': instance.isFamilyFriendly,
      'description': instance.description,
      'allowedRegions': instance.allowedRegions,
      'latestVideos': instance.latestVideos,
    };
